added cortex
particuleio/terraform-kubernetes-addons pull request #20
Opened 2021-02-12 23:07 UTC by apmartins85

Added:
- cortex.tf;
- template;
- variable cortex.

2021-02-13 13:23 UTC, ArchiFleKs commented
We do not support Kiam anymore for AWS. There is no plan to readd it. Is it something required ? Or is IRSA enough ?

2021-02-18 09:11 UTC, ArchiFleKs commented
@Mergifyio refresh

2021-03-04 08:22 UTC, apmartins85 commented
removed kiam;
bumped cortex version;
cleaning up tpl file

2021-03-04 08:35 UTC, ArchiFleKs requested changes

2021-03-04 08:35 UTC, ArchiFleKs commented on templates/cortex-values.yaml
> +config:
are all these values non default-one ? if they are not custom configuration, we should let them empty. Also to allow terraform interpolation if needed they sould go in `local.values_cortex` (I know it bloats the code a little but all the other addons are made like this)

2021-03-04 08:35 UTC, ArchiFleKs commented on cortex.tf
> +      namespace                 = "cortex"
maybe default namespace should be the same as prometheus to avoid network policy issue. So maybe `monitoring` ?

2021-03-04 08:35 UTC, ArchiFleKs commented on cortex.tf
> +  count = local.cortex["enabled"] ? 1 : 0
could you also implement the `create_ns` logic like in the other addons for example [here](https://github.com/particuleio/terraform-kubernetes-addons/blob/main/karma.tf)

2021-03-04 08:35 UTC, ArchiFleKs commented on cortex.tf
> +  serviceAccount:
`name: local.cortex["service_account_name"]`

2021-03-04 08:35 UTC, ArchiFleKs commented on cortex.tf
> +  values_cortex = <<VALUES
these values does not seems to be the values for cortex https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml but the values from cluster autoscaler

2021-03-04 08:35 UTC, ArchiFleKs commented on cortex.tf
> +      cluster_name              = "cluster"
cluster name is already computed and is a available as `var.cluster-name`

2021-03-04 08:38 UTC, ArchiFleKs commented
@apmartins85 also the docs should be updated https://github.com/particuleio/terraform-kubernetes-addons#doc-generation

https://github.com/particuleio/terraform-kubernetes-addons/runs/2029317527?check_suite_focus=true

2022-07-17 01:57 UTC, closed without merging