fix: move karpenter ECR auth token and provider out of the module
particuleio/terraform-kubernetes-addons pull request #2067
Opened 2023-06-05 06:05 UTC by oleksiimorozenko

# [Pull request title](fix: move karpenter ECR auth token and provider out of the module)

## Description

Defining provider and related resources (data source) in the module can break even plan if the user running Terraform is assuming role (i.e. doesn't have any permissions assigned to itself but assume role) even if Karpenter module is disabled

The plan fails with `Error: getting ECR Public authorization token: AccessDeniedException: User: arn:aws:iam::<account-id>:user/username is not authorized to perform: ecr-public:GetAuthorizationToken on resource: * because no identity-based policy allows the ecr-public:GetAuthorizationToken action` in this case

It's better instead to define the provider in the root module as the [dependent module's example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/6c56e2ad20057a5672526b5484df96806598a4e2/examples/karpenter/main.tf#L51) shows
This PR solves the problem when the provider block looks like this:
`provider "aws" {
  region = var.aws_region
  assume_role {
    session_name = "terraform-role"
    role_arn     = "arn:aws:iam::<account-id>:role/rolename"
  }
}
`

### Checklist

- [ ] CI tests are passing
- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/particuleio/terraform-kubernetes-addons/#doc-generation

2023-06-15 20:06 UTC, oleksiimorozenko commented
@ArchiFleKs @rguichard any chance it will be approved?

2023-06-15 20:54 UTC, rguichard commented
> @ArchiFleKs @rguichard any chance it will be approved?

Don't worry we will review it! Thx a lot for your contribution!

2023-06-21 09:57 UTC, ArchiFleKs approved these changes

2023-06-21 09:58 UTC, ArchiFleKs requested changes

2023-06-21 19:11 UTC, oleksiimorozenko commented on modules/aws/.terraform-docs.yml
> -  lockfile: false
Seems like I've deleted it accidentally
Put it back already

2023-06-22 07:19 UTC, ArchiFleKs approved these changes

2023-06-22 07:20 UTC, ArchiFleKs commented
@oleksiimorozenko could you rebase please

2023-06-26 00:07 UTC, merged