Allow configuration of non default aws partition
particuleio/terraform-kubernetes-addons pull request #334
Opened 2021-07-16 15:02 UTC by travertischio

# Pull request title

Allow configuration of non default aws partition

## Description

This module cannot be used currently in partitions that are not "aws". This change allows the configuration of the partition for arn strings while maintaining the current default.

### Checklist

- [x] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/particuleio/terraform-kubernetes-addons/#doc-generation

2021-07-17 20:01 UTC, ArchiFleKs commented
@travertischio thanks for the PR :) I don't have time to test it at the moment, did you test it on your end ? What is the purpose of the aws partition in this case?

2021-07-18 14:25 UTC, travertischio commented
This code is working for me currently.
The partitions are essentially separate aws infrastructure for areas that can't be part of the standard public cloud.
You can see [here](https://docs.amazonaws.cn/en_us/general/latest/gr/aws-arns-and-namespaces.html) that the options are
- `aws` Amazon Regions
- `aws-cn` China Regions
- `aws-us-gov` AmazonGovCloud (US) Regions

2021-07-18 21:04 UTC, ArchiFleKs requested changes
Alright, thanks for the explanation and your contribution. Could you put the new variable in variables-aws.tf and not variables.tf. 

Variables.tf is a symlink common to all modules and it makes no sense outside of the AWS module.

2021-07-20 08:20 UTC, ArchiFleKs approved these changes

2021-07-20 08:22 UTC, merged